### ISSUE TITLE
Build error with Julia 0.4.6 os OSX 10.11.6

### ISSUE THREAD

**Issue by martinzh** [JuliaWeb/MbedTLS.jl#69]
Trying to build MbedTLS from the Julia REPL I obtain the following error:

```
julia> Pkg.build("MbedTLS")
INFO: Building Homebrew
Already up-to-date.
INFO: Building MbedTLS
===============================[ ERROR: MbedTLS ]===============================

LoadError: Provider BinDeps.PackageManager failed to satisfy dependency libmbedtls
while loading /Users/mzumaya/.julia/v0.4/MbedTLS/deps/build.jl, in expression starting on line 74

================================================================================

=============================================[ BUILD ERRORS ]==============================================

WARNING: MbedTLS had build errors.

 - packages with build errors remain installed in /Users/mzumaya/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("MbedTLS")`
 - build a single package by running its `deps/build.jl` script

===========================================================================================================
```

apparently the problem is with `libmbedtls`, but I haven't found any leads to solve the problem, I've already deleted the Homebrew folder in `.julia` and reinstalled it with  `Pkg.add("Homebrew")` without any success, despite there's a file called `libmbedtls.a` in `/Users/mzumaya/.julia/v0.4/Homebrew/deps/usr/Cellar/mbedtls/2.3.0_1/lib`

**Comment by malmaud** [comment]
There was an issue with a recent Homebrew change. It's fixed now.

**Comment by martinzh** [comment]
After doing `Pkg.checkout("MbedTLS")`, `Pkg.checkout("MbedTLS")` and `Pkg.build()` the same error persists
